version: "3.9"

services:
  fastapi:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: fastapi
    container_name: fastapi
    # depends_on:
    #   - postgres
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - fluxo-agil-network

  # postgres:
  #   image: postgres
  #   hostname: postgres
  #   container_name: postgres
  #   restart: on-failure
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   networks:
  #     - fluxo-agil-network

# volumes:
#   postgres:
#     driver: local

networks:
  fluxo-agil-network:
    external: true
